apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s-homelab
spec:
  api:
    address: 0.0.0.0
    port: 6443
    k0sApiPort: 9443
  
  controllerManager: {}
  
  scheduler: {}
  
  storage:
    type: etcd
  
  network:
    kubeProxy:
      disabled: false
    kuberouter:
      autoMTU: true
    calico: null
    
  podCIDR: "10.244.0.0/16"
  serviceCIDR: "10.96.0.0/12"
  
  extensions:
    helm:
      repositories:
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
      - name: jetstack
        url: https://charts.jetstack.io
      - name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
      
      charts:
      - name: ingress-nginx
        chartname: ingress-nginx/ingress-nginx
        version: "4.7.1"
        namespace: ingress-nginx
        values: |
          controller:
            service:
              type: LoadBalancer
            config:
              use-forwarded-headers: "true"
      
      - name: cert-manager
        chartname: jetstack/cert-manager
        version: "v1.12.0"
        namespace: cert-manager
        values: |
          installCRDs: true
          
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler