apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s-homelab
spec:
  api:
    address: 0.0.0.0
    port: 6443
    k0sApiPort: 9443
  
  controllerManager: {}
  
  scheduler: {}
  
  storage:
    type: etcd
  
  network:
    kubeProxy:
      disabled: false
    kuberouter:
      autoMTU: true
    calico: null
    
  podCIDR: "10.244.0.0/16"
  serviceCIDR: "10.96.0.0/12"
  
  extensions:
    helm:
      repositories: []
      charts: []
          
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler