apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weaveworks-oci-charts
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: weaveworks-oci-charts
        namespace: flux-system
      interval: 1m
  values:
    adminUser:
      create: true
      username: admin
    service:
      type: ClusterIP
    ingress:
      enabled: false