apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  values:
    replicaCount: 3
    service:
      type: LoadBalancer
    ingress:
      enabled: false