apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-init-script
  namespace: immich
data:
  init.sh: |
    #!/bin/bash
    set -e
    
    echo "Waiting for Immich server to be ready..."
    until curl -f http://immich-server:2283/api/server/ping > /dev/null 2>&1; do
      echo "Waiting for Immich server..."
      sleep 5
    done
    
    echo "Immich server is ready, checking if admin user exists..."
    
    # Check if admin user already exists
    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
      -X POST http://immich-server:2283/api/auth/login \
      -H "Content-Type: application/json" \
      -d '{"email":"admin@07c.me","password":"admin123"}' || echo "000")
    
    if [ "$RESPONSE" = "201" ] || [ "$RESPONSE" = "200" ]; then
      echo "Admin user already exists, skipping initialization"
      exit 0
    fi
    
    echo "Creating admin user..."
    curl -X POST http://immich-server:2283/api/auth/admin-sign-up \
      -H "Content-Type: application/json" \
      -d '{
        "email": "admin@07c.me",
        "password": "admin123",
        "name": "Admin User"
      }' || echo "Admin user creation may have failed or user already exists"
    
    echo "Immich initialization completed"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: immich-init
  namespace: immich
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: curlimages/curl:8.5.0
        command: ["/bin/sh"]
        args: ["/scripts/init.sh"]
        volumeMounts:
        - name: init-script
          mountPath: /scripts
        env:
        - name: IMMICH_SERVER_URL
          value: "http://immich-server:2283"
      volumes:
      - name: init-script
        configMap:
          name: immich-init-script
          defaultMode: 0755
  backoffLimit: 5